### ISSUE TITLE
魅族Flyme 7，系统升级后，bug；

### ISSUE THREAD

**Issue by Dordong** [yanzhenjie/AndPermission#247]
Intent intent = new Intent("com.meizu.safe.security.SHOW_APPSEC");
        intent.putExtra("packageName", context.getPackageName());
        intent.setComponent(new ComponentName("com.meizu.safe", "com.meizu.safe.security.AppSecActivity"));
        return intent;

**Comment by Dordong** [comment]
@yanzhenjie 严老大，今天刚刚升级flyme7.碰到这个问题，跟你反馈一下～

**Comment by yanzhenjie** [comment]
不好意思啊，你描述的我没看懂具体是什么问题。

**Comment by Dordong** [comment]
奔溃～

**Comment by Dordong** [comment]
java.lang.SecurityException: Permission Denial: starting Intent { act=com.meizu.safe.security.SHOW_APPSEC flg=0x10000000 cmp=com.meizu.safe/.security.AppSecActivity (has extras) } from ProcessRecord{f3ef28e 21507:com.****.*******.test/u0a197} (pid=21507, uid=10197) not exported from uid 1000
                                                                           at android.os.Parcel.readException(Parcel.java:1683)
                                                                           at android.os.Parcel.readException(Parcel.java:1636)
                                                                           at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3472)
                                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1526)
                                                                           at android.app.ContextImpl.startActivity(ContextImpl.java:821)
                                                                           at android.app.ContextImpl.startActivity(ContextImpl.java:798)
                                                                           at android.content.ContextWrapper.startActivity(ContextWrapper.java:358)

**Comment by Dordong** [comment]
qq群里也是我@你。。打扰了

**Comment by yanzhenjie** [comment]
Android系统版本是多少？
你那边能否测试后提供一下打开Setting的方法，另外你可以先试试这段代码打开后是否有设置权限的选项：
```java
Context context = ...;
Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
intent.setData(Uri.fromParts("package", context.getPackageName(), null));
context.startActivity(intent);
```

**Comment by Dordong** [comment]
android版本 7.0
flyme版本 7.0.0.0A；
你提供的代码可以打开魅族应用管理界面，并非之前的直接进入的权限设置页面。不过借鉴滴滴，一直是这么干的。

**Comment by yanzhenjie** [comment]
是否有**权限管理**这个Item，或者类似功能的Item，如果有我就知道怎么做了。

**Comment by Dordong** [comment]
有的
