### ISSUE TITLE
 Missing android.support.FILE_PROVIDER_PATHS meta-data

### ISSUE THREAD

**Issue by hhaappy163** [yanzhenjie/AndPermission#269]
java.lang.RuntimeException: Unable to get provider com.yanzhenjie.permission.FileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6242)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
                                                       at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                    Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                       at com.yanzhenjie.permission.FileProvider.parsePathStrategy(FileProvider.java:185)
                                                       at com.yanzhenjie.permission.FileProvider.getPathStrategy(FileProvider.java:167)
                                                       at com.yanzhenjie.permission.FileProvider.attachInfo(FileProvider.java:87)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722) 
                                                       at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                       at android.os.Looper.loop(Looper.java:164) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by yanzhenjie** [comment]
This may be your compilation environment problem, or 64k problem, no more information, I can not help you.
