### ISSUE TITLE
一加1手机应用禁止相机权限，一直走进onGrant()

### ISSUE THREAD

**Issue by jackvicki** [yanzhenjie/AndPermission#271]
环境：一加1代手机，Android 6.0.1， targetSdkVersion <23
申请权限：相机
问题：使用你的demo工程，禁止相机权限后能正常的弹出去设置的提示框。但是在我自己的应用里面禁止相机权限，一样的代码逻辑，却一直返回的是权限正常。打断点跟进去，发现在StandardChecker里面进行hasPermission判断的时候，
`int result = context.checkPermission(permission, android.os.Process.myPid(), android.os.Process.myUid());`
我自己的应用返回的0；跟进到源码ActvityManagerService有这段：
`
int checkComponentPermission(String permission, int pid, int uid,
            int owningUid, boolean exported) {
        if (pid == MY_PID) {
            return PackageManager.PERMISSION_GRANTED;
        }
        return ActivityManager.checkComponentPermission(permission, uid,
                owningUid, exported);
    }
`
到不懂为什么会出现这种情况，麻烦大神帮忙分析下。

**Comment by zhoukai0203** [comment]
1加3t手机，rc6相机权限没有问题，定位权限有问题， 用rc10最新的，相机权限一直提示要获取，定位权限好了，加急解决下呗 @yanzhenjie

**Comment by yanzhenjie** [comment]
问题是相机权限一直提示获取，我很难判断出问题是什么。没有其它详细的描述或者能帮助判断问题信息吗？

**Comment by zhoukai0203** [comment]
E/AndPermission: Please check the onGranted() method body for bugs.
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.xyre.hio.develop/cache/default_photo_crop_tmp.jpg exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2356)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1795)
        at android.app.Activity.startActivityForResult(Activity.java:4495)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4453)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at com.xyre.hio.common.utils.SysPhotoCropper.cropForCamera(SysPhotoCropper.kt:74)
        at com.xyre.hio.ui.user.InfoActivity$requestPermission$1.onAction(InfoActivity.kt:106)
        at com.xyre.hio.ui.user.InfoActivity$requestPermission$1.onAction(InfoActivity.kt:31)
        at com.yanzhenjie.permission.runtime.MRequest.callbackSucceed(MRequest.java:139)
        at com.yanzhenjie.permission.runtime.MRequest.dispatchCallback(MRequest.java:126)
        at com.yanzhenjie.permission.runtime.MRequest.start(MRequest.java:99)
        at com.xyre.hio.ui.user.InfoActivity.requestPermission(InfoActivity.kt:116)
        at com.xyre.hio.ui.user.InfoActivity.access$requestPermission(InfoActivity.kt:31)
        at com.xyre.hio.ui.user.InfoActivity$showChoosePhotoDialog$$inlined$let$lambda$1.onClickCamera(InfoActivity.kt:93)
        at com.xyre.hio.widget.dialog.DialogChoosePictureFragment$onActivityCreated$2.onClick(DialogChoosePictureFragment.kt:47)
        at android.view.View.performClick(View.java:6303)
        at android.view.View$PerformClick.run(View.java:24828)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
没有读取的权限，rc6没问题，rc10出的问题

**Comment by yanzhenjie** [comment]
是你代码的问题，上面已经明确说了你的`onGrant()`方法可能有bug。

**Comment by zhoukai0203** [comment]
private fun requestPermission(vararg permissions: String) {
        AndPermission.with(this)
                .runtime()
                .permission(*permissions)
                .onGranted {
                    sysPhotoCropper.cropForCamera()
                }
                .onDenied { deniedPermissions ->
                    for(item in deniedPermissions){
                        LogUtils.i("permission:$item")
                    }
                    if (AndPermission.hasAlwaysDeniedPermission(this@InfoActivity, deniedPermissions)) {
                        DialogUtils.showSettingDialog(this, R.string.permission_message_always_failed_camera)
                    }
                }
                .start()
    }


requestPermission(Permission.READ_EXTERNAL_STORAGE,
                            Permission.WRITE_EXTERNAL_STORAGE,Permission.CAMERA) 没觉得有问题啊，毕竟rc6是好的

**Comment by yanzhenjie** [comment]
The questioner did not respond and closed.
