### ISSUE TITLE
小米4(系统版本 android6.0.1,api23)上面,申请相机权限ANR.

### ISSUE THREAD

**Issue by daixiansen** [yanzhenjie/AndPermission#285]
在小米自带权限管理系统将相机关闭掉后,申请相机权限ANR,出错信息如下,相机open好像要在子线程中执行.
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x74b095c8 self=0xb4cf6500
  | sysTid=13642 nice=-4 cgrp=default sched=0/0 handle=0xb6f59b34
  | state=S schedstat=( 11802038505 1593348694 7720 ) utm=1003 stm=177 core=3 HZ=100
  | stack=0xbe297000-0xbe299000 stackSize=8MB
  | held mutexes=
  native: #00 pc 00040ab4  /system/lib/libc.so (__ioctl+8)
  native: #01 pc 00047531  /system/lib/libc.so (ioctl+14)
  native: #02 pc 0001ea69  /system/lib/libbinder.so (_ZN7android14IPCThreadState14talkWithDriverEb+132)
  native: #03 pc 0001f0bb  /system/lib/libbinder.so (_ZN7android14IPCThreadState15waitForResponseEPNS_6ParcelEPi+38)
  native: #04 pc 0001f327  /system/lib/libbinder.so (_ZN7android14IPCThreadState8transactEijRKNS_6ParcelEPS1_j+306)
  native: #05 pc 0001a19b  /system/lib/libbinder.so (_ZN7android8BpBinder8transactEjRKNS_6ParcelEPS1_j+30)
  native: #06 pc 0001dd2b  /system/lib/libcamera_client.so (???)
  native: #07 pc 0002187b  /system/lib/libcamera_client.so (_ZN7android10CameraBaseINS_6CameraENS_12CameraTraitsIS1_EEE7connectEiRKNS_8String16Ei+130)
  native: #08 pc 000183fd  /system/lib/libcamera_client.so (_ZN7android6Camera7connectEiRKNS_8String16Ei+4)
  native: #09 pc 000a3ce3  /system/lib/libandroid_runtime.so (???)
  native: #10 pc 00a92109  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_hardware_Camera_native_1setup__Ljava_lang_Object_2IILjava_lang_String_2+140)
  at android.hardware.Camera.native_setup(Native method)
  at android.hardware.Camera.cameraInitVersion(Camera.java:508)
  at android.hardware.Camera.cameraInitNormal(Camera.java:513)
  at android.hardware.Camera.<init>(Camera.java:538)
  at android.hardware.Camera.open(Camera.java:397)
  at com.yanzhenjie.permission.checker.CameraTest.test(CameraTest.java:43)
  at com.yanzhenjie.permission.StrictChecker.checkCamera(StrictChecker.java:134)
  at com.yanzhenjie.permission.checker.StrictChecker.hasPermission(StrictChecker.java:72)
  at com.yanzhenjie.permission.checker.StrictChecker.hasPermission(StrictChecker.java:43)
  at com.yanzhenjie.permission.checker.DoubleChecker.hasPermission(DoubleChecker.java:35)

**Comment by raybest4u** [comment]
How to fix?

**Comment by yanzhenjie** [comment]
早就修复了，升级到最新版本即可。
