### ISSUE TITLE
Android 7.0 NullPointerException，6.0运行正常

### ISSUE THREAD

**Issue by wyxiloveu** [yanzhenjie/AndPermission#29]
03-07 08:33:12.666 29428-29428/? E/AndroidRuntime: FATAL EXCEPTION: main
 Process: www.diandou, PID: 29428
 java.lang.RuntimeException: Unable to start activity ComponentInfo{www.diandou/www.diandou.activity.SplashActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'yanzhenjie.permission.e yanzhenjie.permission.e.a(int)' on a null object reference
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2722)
     at android.app.ActivityThread.-wrap12(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6114)
     at java.lang.reflect.Method.invoke(Native Method)
     at android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
     at android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
  Caused by: java.lang.NullPo

**Comment by yanzhenjie** [comment]
麻烦把非混淆时的错误信息贴出来一下，方便我们判断是哪边的问题。

**Comment by wyxiloveu** [comment]
没有混淆的包暂时还没有出现空指针，之前是线上的报异常了。

**Comment by wyxiloveu** [comment]
问题大概出现在爱加密这边，我上周做了一个360加固的包，在三台之前出问题的小米5设备（7.0+）上可以正常使用。
