### ISSUE TITLE
AndPermission.getFileUri报错

### ISSUE THREAD

**Issue by GreenhairTurtle** [yanzhenjie/AndPermission#325]
如题，当调用这个方法时
```Java
java.lang.StringIndexOutOfBoundsException: length=56; index=57
        at java.lang.String.substring(String.java:1939)
        at com.yanzhenjie.permission.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:286)
        at com.yanzhenjie.permission.FileProvider.getUriForFile(FileProvider.java:92)
        at com.yanzhenjie.permission.AndPermission.getFileUri(AndPermission.java:301)
        at com.wecardio.utils.IntentUtils.getOpenCameraIntent(IntentUtils.java:32)
```

方法如下
```Java
 public static Intent getOpenCameraIntent(Context context) {
    Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
    intent.putExtra(MediaStore.EXTRA_OUTPUT,
        AndPermission.getFileUri(context, context.getExternalCacheDir()));
    return intent;
  }
```

getUriForFile(File file)方法
```Java
 public Uri getUriForFile(File file) {
            String path;
            try {
                path = file.getCanonicalPath();
            } catch (IOException e) {
                throw new IllegalArgumentException("Failed to resolve canonical path for " + file);
            }

            Map.Entry<String, File> mostSpecific = null;
            for (Map.Entry<String, File> root : mRoots.entrySet()) {
                final String rootPath = root.getValue().getPath();
                boolean invalidMost = mostSpecific == null || rootPath.length() > mostSpecific.getValue().getPath().length();
                if (path.startsWith(rootPath) && invalidMost) {
                    mostSpecific = root;
                }
            }

            if (mostSpecific == null) {
                throw new IllegalArgumentException("Failed to find configured root that contains " + path);
            }

            final String rootPath = mostSpecific.getValue().getPath();
            if (rootPath.endsWith("/")) {
                path = path.substring(rootPath.length());
            } else {
                path = path.substring(rootPath.length() + 1);
            }

            path = Uri.encode(mostSpecific.getKey()) + '/' + Uri.encode(path, "/");
            return new Uri.Builder().scheme("content").authority(mAuthority).encodedPath(path).build();
        }
```

```Java
if (rootPath.endsWith("/")) {
       path = path.substring(rootPath.length());
 } else {
       path = path.substring(rootPath.length() + 1);
 }
```

看起来这个错误。。。

望修复！谢谢

**Comment by yanzhenjie** [comment]
须是file对应的path。

**Comment by GreenhairTurtle** [comment]
了解，不好意思，使用错了
谢谢！
