### ISSUE TITLE
在unity对应的Activity中申请权限崩溃，崩溃原因为空指针

### ISSUE THREAD

**Issue by jxl715** [yanzhenjie/AndPermission#329]
08-10 15:16:12.429 25485-26045/com.ubt.jimu E/Unity: 开启蓝牙搜索
08-10 15:16:12.429 25485-25485/com.ubt.jimu I/CrashReport-Native: Set native info: isAppForeground(false)
08-10 15:16:12.469 25485-25485/com.ubt.jimu D/HwCust: Create obj success use class android.app.HwCustHwWallpaperManagerImpl
08-10 15:16:12.471 25485-25485/com.ubt.jimu D/CrashReport: >>> com.yanzhenjie.permission.PermissionActivity onCreated <<<
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getClassName()' on a null object reference
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at com.ubt.jimu.ho.AmsHookBinderInvocationHandler.invoke(AmsHookBinderInvocationHandler.java:47)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at $Proxy3.startActivity(Unknown Source)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1637)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:4679)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.Activity.requestPermissions(Activity.java:3923)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at com.yanzhenjie.permission.PermissionActivity.onCreate(PermissionActivity.java:120)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.Activity.performCreate(Activity.java:6372)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.os.Looper.loop(Looper.java:150)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5665)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
08-10 15:16:12.474 25485-25485/com.ubt.jimu W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
08-10 15:16:12.492 25485-25485/com.ubt.jimu D/ActivityThread: add activity client record, r= ActivityRecord{e593d44 token=android.os.BinderProxy@f0e3e57 {com.ubt.jimu/com.yanzhenjie.permission.PermissionActivity}} token= android.os.BinderProxy@f0e3e57
08-10 15:16:12.492 25485-25485/com.ubt.jimu D/CrashReport: >>> com.yanzhenjie.permission.PermissionActivity onResumed <<<
08-10 15:16:12.492 25485-25485/com.ubt.jimu I/CrashReport-Native: Set native info: isAppForeground(true)
08-10 15:16:12.500 25485-25642/com.ubt.jimu D/mali_winsys: new_window_surface returns 0x3000

**Comment by jxl715** [comment]
看错了，崩溃地点不是在AndPermission中
