### ISSUE TITLE
请求权限异常android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by JhoBor** [yanzhenjie/AndPermission#338]
荣耀9，魅族16两款机型（android系统在8.0以上）在请求权限时都出现异常：android.content.res.Resources$NotFoundException: Resource ID #0x0
具体报错如下（部分包名用***代替）：
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.***.***/com.***.***.ui.activity.SetupActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:279)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2310)
        at android.content.res.Resources.getLayout(Resources.java:1293)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
        at android.support.v7.app.AlertController.installContent(AlertController.java:231)
        at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:278)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:528)
        at android.app.Dialog.show(Dialog.java:389)
        at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:1006)
        at com.***.***.ui.activity.SetupActivity.handleRationale(SetupActivity.java:88)
        at com.***.***.ui.activity.SetupActivity.access$100(SetupActivity.java:25)
        at com.***.***.ui.activity.SetupActivity$3.showRationale(SetupActivity.java:53)
        at com.***.***.ui.activity.SetupActivity$3.showRationale(SetupActivity.java:50)
        at com.yanzhenjie.permission.runtime.MRequest.start(MRequest.java:94)
        at com.***.***.ui.activity.SetupActivity.requestPermissions(SetupActivity.java:69)
        at com.***.***.ui.activity.SetupActivity.onCreate(SetupActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by yanzhenjie** [comment]
我的判断结果是不知道是你们的代码还是AndPermissino引起的，哪个都有可能。

看报错信息应该可以定位在这几行：
```
at com.***.***.ui.activity.SetupActivity.handleRationale(SetupActivity.java:88)
at com.***.***.ui.activity.SetupActivity.access$100(SetupActivity.java:25)
at com.***.***.ui.activity.SetupActivity$3.showRationale(SetupActivity.java:53)
at com.***.***.ui.activity.SetupActivity$3.showRationale(SetupActivity.java:50)
at com.yanzhenjie.permission.runtime.MRequest.start(MRequest.java:94)
at com.***.***.ui.activity.SetupActivity.requestPermissions(SetupActivity.java:69)
at com.***.***.ui.activity.SetupActivity.onCreate(SetupActivity.java:43)
```

如果你不能自行确定出错误是什么引起的话，你可以把这行附近的代码贴一下：
```
at com.***.***.ui.activity.SetupActivity.handleRationale(SetupActivity.java:88)
```

**Comment by JhoBor** [comment]
感谢开发者及时的回复，我现在才看到，真是不好意思！        我尝试了一下其它的第三方动态权限请求库，发现问题依然存在，可以肯定不是由于这个库造成的。由于报错没有指明行数，所以我也调试了好久，最后发现问题出在v7兼容包的dialog类中，我改引用app.diolag，问题就解决了。        我一直在用AndPermission，以后也会继续支持AndPermission，感谢幕后默默付出的人发自我的华为手机-------- 原始邮件 --------主题：Re: [yanzhenjie/AndPermission] 请求权限异常android.content.res.Resources$NotFoundException (#338)发件人：Zhenjie Yan 收件人：yanzhenjie/AndPermission 抄送：Benkie ,Author 我的判断结果是不知道是你们的代码还是AndPermissino引起的，哪个都有可能。
看报错信息应该可以定位在这几行：
at com.***.***.ui.activity.SetupActivity.handleRationale(SetupActivity.java:88)
at com.***.***.ui.activity.SetupActivity.access$100(SetupActivity.java:25)
at com.***.***.ui.activity.SetupActivity$3.showRationale(SetupActivity.java:53)
at com.***.***.ui.activity.SetupActivity$3.showRationale(SetupActivity.java:50)
at com.yanzhenjie.permission.runtime.MRequest.start(MRequest.java:94)
at com.***.***.ui.activity.SetupActivity.requestPermissions(SetupActivity.java:69)
at com.***.***.ui.activity.SetupActivity.onCreate(SetupActivity.java:43)

如果你不能自行确定出错误是什么引起的话，你可以把这行附近的代码贴一下：
at com.***.***.ui.activity.SetupActivity.handleRationale(SetupActivity.java:88)


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yanzhenjie/AndPermission","title":"yanzhenjie/AndPermission","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/yanzhenjie/AndPermission"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yanzhenjie in #338: 我的判断结果是不知道是你们的代码还是AndPermissino引起的，哪个都有可能。\r\n\r\n看报错信息应该可以定位在这几行：\r\n```\r\nat com.***.***.ui.activity.SetupActivity.handleRationale(SetupActivity.java:88)\r\nat com.***.***.ui.activity.SetupActivity.access$100(SetupActivity.java:25)\r\nat com.***.***.ui.activity.SetupActivity$3.showRationale(SetupActivity.java:53)\r\nat com.***.***.ui.activity.SetupActivity$3.showRationale(SetupActivity.java:50)\r\nat com.yanzhenjie.permission.runtime.MRequest.start(MRequest.java:94)\r\nat com.***.***.ui.activity.SetupActivity.requestPermissions(SetupActivity.java:69)\r\nat com.***.***.ui.activity.SetupActivity.onCreate(SetupActivity.java:43)\r\n```\r\n\r\n如果你不能自行确定出错误是什么引起的话，你可以把这行附近的代码贴一下：\r\n```\r\nat com.***.***.ui.activity.SetupActivity.handleRationale(SetupActivity.java:88)\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/yanzhenjie/AndPermission/issues/338#issuecomment-415258087"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yanzhenjie/AndPermission/issues/338#issuecomment-415258087",
"url": "https://github.com/yanzhenjie/AndPermission/issues/338#issuecomment-415258087",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [yanzhenjie/AndPermission] 请求权限异常android.content.res.Resources$NotFoundException (#338)",
"sections": [
{
"text": "",
"activityTitle": "**Zhenjie Yan**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yanzhenjie",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"yanzhenjie/AndPermission\",\n\"issueId\": 338,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"yanzhenjie/AndPermission\",\n\"issueId\": 338\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/yanzhenjie/AndPermission/issues/338#issuecomment-415258087"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 371376787\n}"
}
],
"themeColor": "26292E"
}
]
