### ISSUE TITLE
Notification permission, url of setup page

### ISSUE THREAD

**Issue by MsKnow** [yanzhenjie/AndPermission#412]
调用executor.execute();崩溃
崩溃信息如下
E/ActivityManager: 12345, set task null.ActivityRecord{cc9f433 u0 com.huahua.testing/com.yanzhenjie.permission.bridge.BridgeActivity t-1 f}
    java.lang.RuntimeException
        at com.android.server.am.ActivityRecord.setTask(ActivityRecord.java:785)
        at com.android.server.am.TaskRecord.removeActivity(TaskRecord.java:1497)
        at com.android.server.am.TaskRecord.removeActivity(TaskRecord.java:1478)
        at com.android.server.am.ActivityStack.removeActivityFromHistoryLocked(ActivityStack.java:4607)
        at com.android.server.am.ActivityStack.removeHistoryRecordsForAppLocked(ActivityStack.java:4987)
        at com.android.server.am.ActivityStack.handleAppDiedLocked(ActivityStack.java:5610)
        at com.android.server.am.ActivityStackSupervisor.handleAppDiedLocked(ActivityStackSupervisor.java:2155)
        at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:6711)
        at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:6898)
        at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1844)
        at android.os.BinderProxy.sendDeathNotice(Binder.java:1300)

**Comment by yanzhenjie** [comment]
Please provide the following information:
1. Related code snippet.
2. Android system information.
3. Project's compileSdkVersion, buildToolsVersion, and targetSdkVersion

Also trouble you to execute this code and provide me with the exception information that happened:
```java
Intent settingIntent = new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS);
settingIntent.putExtra(Settings.EXTRA_APP_PACKAGE, getPackageName());
startActivityForResult(settingIntent, BridgeRequest.TYPE_NOTIFY);
```

**Comment by MsKnow** [comment]
1.
```
AndPermission.with(context).notification().permission()
                    .rationale((context1, data, executor) -> {
                        Log.e("AndPermission","-notification-rationale->"+data);
                        executor.execute();
                    })
                    .onGranted(data -> {
                Log.e("AndPermission","-notification-onGranted->"+data);
            }).onDenied(data -> {
                Log.e("AndPermission","-notification-onDenied->"+data);
            }).start();
```
2. 
android version 8.1.0
model DE106
3. 
compileSdkVersion 28
buildToolsVersion '28.0.3'
targetSdkVersion 26

Your code crashes and log is as follows
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APP_NOTIFICATION_SETTINGS (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1949)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1619)
        at android.app.Activity.startActivityForResult(Activity.java:4741)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4699)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at com.huahua.testing.view.PermissionDialog.lambda$initView$4(PermissionDialog.java:87)
        at com.huahua.testing.view.-$$Lambda$PermissionDialog$mvUQDEZ-a9ZjJEY0-AHQkh7_0TE.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6428)
        at android.view.View$PerformClick.run(View.java:25365)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6905)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

**Comment by yanzhenjie** [comment]
I did some testing and there were no problems with other brands of phones. This may be a problem with this phone, because I don't have this phone, so I would like to ask you to test and provide the code to open the notification settings correctly, thank you very much.

Otherwise this problem I may wirelessly extend the resolution date.

**Comment by MsKnow** [comment]
Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
intent.setData(Uri.fromParts("package", context.getPackageName(), null));
context.startActivity(intent);
I opened the application Settings page with the above code where there is a switch to set notification permissions directly
