### ISSUE TITLE
java.lang.RuntimeException: Error receiving broadcast Intent

### ISSUE THREAD

**Issue by ShinyZeng** [yanzhenjie/AndPermission#421]
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.yanzhenjie.permission.bridge flg=0x10 } in com.yanzhenjie.permission.bridge.Messenger@2586506
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52651(LoadedApk.java:1329)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.yanzhenjie.permission.bridge.Messenger@2586506
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1197)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1459)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:655)
	at com.yanzhenjie.permission.bridge.Messenger.unRegister(Messenger.java:49) (#pluginId:host#)
	at com.yanzhenjie.permission.bridge.RequestExecutor.onCallback(RequestExecutor.java:96) (#pluginId:host#)
	at com.yanzhenjie.permission.bridge.Messenger.onReceive(Messenger.java:54) (#pluginId:host#)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52651(LoadedApk.java:1319)
	... 9 more

**Comment by ShinyZeng** [comment]
```
final class RequestExecutor extends Thread implements Messenger.Callback {

    private final BlockingQueue<BridgeRequest> mQueue;
    private BridgeRequest mRequest;
    private Messenger mMessenger;
```
mMessenger maybe has been change when recall onCallback
```
@Override
    public void onCallback() {
        synchronized (this) {
            mMessenger.unRegister(); // crash :Receiver not registered
            mRequest.getCallback().onCallback();
            notify();
        }
    }
```
But I dont has enought log to prove

**Comment by yanzhenjie** [comment]
Received, I will study it.

**Comment by vk2211** [comment]
> Received, I will study it.

用了这个库的时候，每次升级或重装都会有这个crash

**Comment by feicien** [comment]
我这边也遇到了类似的 bug，使用的是 2.0.1 版本

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.yanzhenjie.permission.bridge flg=0x10 } in com.yanzhenjie.permission.bridge.b@3d94127
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_58300(LoadedApk.java:1448)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.yanzhenjie.permission.bridge.b@3d94127
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1292)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1629)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:639)
	at com.yanzhenjie.permission.bridge.b.b(Messenger.java:49)
	at com.yanzhenjie.permission.bridge.c.a(RequestExecutor.java:96)
	at com.yanzhenjie.permission.bridge.b.onReceive(Messenger.java:54)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_58300(LoadedApk.java:1435)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
	at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
```

这个异常只有华为手机才会有：

![企业微信截图_ee4f12e5-0658-484f-9672-fb01514e22cd](https://user-images.githubusercontent.com/1282265/58379204-60c71e80-7fd3-11e9-8e44-c75148845ea1.png)

**Comment by yanzhenjie** [comment]
#436

**Comment by lwj1994** [comment]
2.0.3 版本 这个bug还在 @yanzhenjie   HuaWei/EMOTION Android 9,level 28

**Comment by xiaomayi-zxh** [comment]
2.0.3 版本 在小米max2s 10版本也还是有这个问题
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.xx.andpermission.bridge.Thread-15 flg=0x10 } in com.yanzhenjie.permission.bridge.c@2e89e4e
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1407)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@290af54 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:853)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:329)
        at com.yanzhenjie.permission.g.a.onPreExecute(TaskExecutor.java:42)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:648)
        at com.yanzhenjie.permission.g.a.a(TaskExecutor.java:60)
        at com.yanzhenjie.permission.e.d.b(MRequest.java:115)
        at com.yanzhenjie.permission.bridge.d.a(RequestExecutor.java:115)
        at com.yanzhenjie.permission.bridge.c.onReceive(Messenger.java:54)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1397)
