### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by moonljt521** [yanzhenjie/AndPermission#433]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.yqxue.yqxue/com.yanzhenjie.permission.PermissionActivity}; have you declared this activity in your AndroidManifest.xml?
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1940)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1618)
    at android.app.Activity.startActivityForResult(Activity.java:4501)
    at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
    at android.app.Activity.startActivityForResult(Activity.java:4459)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
    at android.app.Activity.startActivity(Activity.java:4820)
    at android.app.Activity.startActivity(Activity.java:4788)
    at com.yanzhenjie.permission.PermissionActivity.a(PermissionActivity.java:60)
    at com.yanzhenjie.permission.d.c.b(MRequest.java:105)
    at com.yanzhenjie.permission.d.c.m_(MRequest.java:96)
    at com.yqxue.yqxue.e.c.a(PermissionUtil.java:124)
    at com.yqxue.yqxue.e.c.a(PermissionUtil.java:154)

android 版本： 8.1.0
手机型号：Lenovo L38012
报错版本：2.0.0-rc12

**Comment by moonljt521** [comment]
请问您解决了么

**Comment by ChangSpring** [comment]
+1

**Comment by Davi0528** [comment]
+2

**Comment by yanzhenjie** [comment]
This has nothing to do with the project, please refer to here to solve:  
https://developer.android.com/studio/build/multidex

> Already have the same issue, please search for the same issue before creating a new issue.
