### ISSUE TITLE
部分机型ANR，新版本有解决吗，我现在用的2.0.0

### ISSUE THREAD

**Issue by alex2390** [yanzhenjie/AndPermission#440]
io.bugtags.platform.AnrError: Application Not Responding
Caused by: io.bugtags.platform.AnrError$a$a: main (state = RUNNABLE)
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:515)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:474)
	at android.content.ContentResolver.insert(ContentResolver.java:1304)
	at com.yanzhenjie.permission.a.h.a(ContactsWriteTest.java:82)
	at com.yanzhenjie.permission.a.h.a(ContactsWriteTest.java:49)
	at com.yanzhenjie.permission.a.v.e(StrictChecker.java:137)
	at com.yanzhenjie.permission.a.v.a(StrictChecker.java:70)
	at com.yanzhenjie.permission.a.v.a(StrictChecker.java:39)
	at com.yanzhenjie.permission.a.i.a(DoubleChecker.java:32)
	at com.yanzhenjie.permission.d.c.a(MRequest.java:164)
	at com.yanzhenjie.permission.d.c.d(MRequest.java:124)
	at com.yanzhenjie.permission.d.c.n_(MRequest.java:99)
	at com.hx.sobu.ui.general.HomePage.a(HomePage.java:1251)
	at com.hx.sobu.ui.general.HomePage.a(HomePage.java:158)
	at com.hx.sobu.ui.general.HomePage$3.onResponse(HomePage.java:1353)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5845)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

**Comment by yanzhenjie** [comment]
有
