### ISSUE TITLE
必崩

### ISSUE THREAD

**Issue by liaohuyu** [yanzhenjie/AndPermission#447]
2019-05-28 17:26:51.997 2805-2805/com.android.tutuerge E/ActivityThread: Activity com.android.tutuerge.MainActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.Messenger@1fef88d that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.android.tutuerge.MainActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.Messenger@1fef88d that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1498)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1226)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1601)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1574)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1562)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:603)
        at com.yanzhenjie.permission.bridge.Messenger.register(Messenger.java:45)
        at com.yanzhenjie.permission.bridge.RequestExecutor.run(RequestExecutor.java:44)

操作：改变虚拟导航栏的显隐就会出现这个玩意。

**Comment by liaohuyu** [comment]
补充一下，华为8.0手机，测试机有限，oppo7.1手机没发现这个问题。。

**Comment by haonan1** [comment]
我也遇到了，小米 8.0手机

**Comment by yanzhenjie** [comment]
#446
