### ISSUE TITLE
线上的bug，麻烦看下

### ISSUE THREAD

**Issue by z2045217** [yanzhenjie/AndPermission#450]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
       at com.yanzhenjie.permission.checker.StandardChecker.hasPermission(StandardChecker.java:48)
       at com.yanzhenjie.permission.checker.StandardChecker.hasPermission(StandardChecker.java:39)
       at com.yanzhenjie.permission.checker.DoubleChecker.hasPermission(DoubleChecker.java:33)
       at com.yanzhenjie.permission.runtime.MRequest.getDeniedPermissions(MRequest.java:168)
       at com.yanzhenjie.permission.runtime.MRequest.access$300(MRequest.java:40)
       at com.yanzhenjie.permission.runtime.MRequest$2.doInBackground(MRequest.java:122)
       at com.yanzhenjie.permission.runtime.MRequest$2.doInBackground(MRequest.java:119)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by z2045217** [comment]
这个问题。线上崩溃率很高。麻烦作者修改下。

**Comment by yanzhenjie** [comment]
This should not happen unless the permissions you pass in are null.

**Comment by z2045217** [comment]
这个明显是Context为null。。和permissions没关系。

**Comment by baoti** [comment]
应该是用了 AndPermission.with(fragment)，但此时 fragment.getContext() 已经是 null 了。

**Comment by z2045217** [comment]
用户行为我们没有办法控制。但是每次获取权限的时候，响应速度会很慢。这时候用户关闭当前页面。就有可能出现类似错误。
