### ISSUE TITLE
onGranted method body for bugs

### ISSUE THREAD

**Issue by dendrocyte** [yanzhenjie/AndPermission#474]
I made a customized view.
when I test the view in
1. encoded in java
2. integrated with android.support.library
=> work fine

but 
when I integrate with aar of this view
1. encoded in kotlin
2. integrated with androidx
=> work not fined recently

Please check the onGranted() method body for bugs.
    java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at com.example.googlelocation.customView.LocationBtn$1.onSuccess(LocationBtn.java:38)
        at com.example.googlelocation.util.PermissionUtil$2.onAction(PermissionUtil.java:49)
        at com.example.googlelocation.util.PermissionUtil$2.onAction(PermissionUtil.java:44)
        at com.yanzhenjie.permission.runtime.MRequest.callbackSucceed(MRequest.java:143)
        at com.yanzhenjie.permission.runtime.MRequest.access$400(MRequest.java:40)
        at com.yanzhenjie.permission.runtime.MRequest$2.onPostExecute(MRequest.java:128)
        at com.yanzhenjie.permission.runtime.MRequest$2.onPostExecute(MRequest.java:119)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)

**Comment by VincentJ1989** [comment]
how to solve it?

**Comment by dendrocyte** [comment]
It is my fault. No this lib issue.
Have to take care which kind of context you used.
Check the codes at the permission have granted, if any error happens, error listener will catch it and present.

**Comment by VincentJ1989** [comment]
Get it , thx :)
