### ISSUE TITLE
Android 10 Android Q 新特性适配

### ISSUE THREAD

**Issue by nihaohebin** [yanzhenjie/AndPermission#478]
电话权限无法正常申请。希望大佬适配一下儿

**Comment by xfort** [comment]
Android Q 开始，不会获得IMEI GSM 设备号，作者使用的是getDeviceId（）、getSubscriberId（）会返回null或异常，所以判定为无权限。Android Q 开始，只有系统签名APP才能获得设备号IMEI,GSM什么的

**Comment by nihaohebin** [comment]
android.app.IntentReceiverLeaked: Activity com.atgc.mycs.main.welcome.WelcomeActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.Messenger@26d225e that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1596)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1372)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1525)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1498)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1486)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:637)
        at com.yanzhenjie.permission.bridge.Messenger.register(Messenger.java:45)
        at com.yanzhenjie.permission.bridge.RequestExecutor.run(RequestExecutor.java:44)

**Comment by nihaohebin** [comment]
> Android Q 开始，不会获得IMEI GSM 设备号，作者使用的是getDeviceId（）、getSubscriberId（）会返回null或异常，所以判定为无权限。Android Q 开始，只有系统签名APP才能获得设备号IMEI,GSM什么的

好的。

**Comment by tanranran** [comment]
感觉作者弃坑了。。。。。


我擦。。。只能自己维护了。

**Comment by chenyusheng** [comment]
> 备

so，怎么fix？

**Comment by yanzhenjie** [comment]
这个issue里面跟踪所有Android10的问题，例如**外部存储权限**、**设备状态权限**等，请大家把自己遇到的问题汇总在这里。

**Comment by KotlinLan** [comment]
@yanzhenjie 请问电话权限的适配什么时候能更新呢？现在很多mate30系列的用户反馈说即使给了电话权限也没用。

**Comment by yanzhenjie** [comment]
已经发布了2.0.2，修复了目前的bug，兼容了Android10（Q）的（官网文档中已知的）所有权限，请大家试用并反馈，如果有问题会尽快在2.0.2的基础上发布2.0.3版本。

如果反馈请新开Issue，并参考[Issues主页](https://github.com/yanzhenjie/AndPermission/issues)的[如何给AndPermission提Issue](https://github.com/yanzhenjie/AndPermission/issues/493)的建议。

**Comment by shuaimango** [comment]
2.0.3只支持androidx项目，但大部分是support项目，大佬怎么办

**Comment by yanzhenjie** [comment]
@shuaimango  
从Android Support迁移至AndroidX的Google官方文档：  
[https://developer.android.com/jetpack/androidx/migrate](https://developer.android.com/jetpack/androidx/migrate)
