### ISSUE TITLE
2.0.3 release 下载 编译后，通知权限操作，抛异常

### ISSUE THREAD

**Issue by dawsonjiang** [yanzhenjie/AndPermission#506]
2.0.3 release 下载 编译后，通知权限操作，抛异常
com.yanzhenjie.permission.sample E/ActivityThread: Activity com.yanzhenjie.permission.sample.app.MainActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.Messenger@42feaef that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.yanzhenjie.permission.sample.app.MainActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.Messenger@42feaef that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1596)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1329)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1698)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1671)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1659)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
        at com.yanzhenjie.permission.bridge.Messenger.register(Messenger.java:45)
        at com.yanzhenjie.permission.bridge.RequestExecutor.run(RequestExecutor.java:47)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)

-

**Comment by yanzhenjie** [comment]
感谢反馈问题，麻烦你按照我在Issue首页的要求提供一下操作步骤和其他相关信息，不然我很难拿出解决方案。

**Comment by mhh10** [comment]
case BridgeRequest.TYPE_NOTIFY: {
        Intent settingIntent = new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS);
        settingIntent.putExtra(Settings.EXTRA_APP_PACKAGE, getPackageName());
//                    settingIntent.setData(Uri.fromParts("package", getPackageName(), null));
        startActivityForResult(settingIntent, BridgeRequest.TYPE_NOTIFY);
        break;
        
 如上，注释掉BridgeActivity.java ，#168行代码即可。
