### ISSUE TITLE
2.0.3 版本申请相册和拍照权限时 ，崩了。错误如下。

### ISSUE THREAD

**Issue by xiangshiweiyu** [yanzhenjie/AndPermission#507]
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.ms.online.andpermission.bridge.Thread-131 flg=0x10 } in com.yanzhenjie.permission.bridge.Messenger@e90a827
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1407)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at com.yanzhenjie.permission.task.WaitDialog.<init>(WaitDialog.java:32)
        at com.yanzhenjie.permission.task.TaskExecutor.<init>(TaskExecutor.java:35)
        at com.yanzhenjie.permission.runtime.MRequest$1.<init>(MRequest.java:101)
        at com.yanzhenjie.permission.runtime.MRequest.onCallback(MRequest.java:101)
        at com.yanzhenjie.permission.bridge.RequestExecutor.onCallback(RequestExecutor.java:115)
        at com.yanzhenjie.permission.bridge.Messenger.onReceive(Messenger.java:54)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1397)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6815) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by getglory** [comment]
申请权限时，必须传Activity，不能传Application，否则会因为没有主题导致崩溃。
Fragment中：AndPermission.with(getActivity()).runtime().....
Activity中：AndPermission.with(this).runtime().....

**Comment by xiangshiweiyu** [comment]
嗯嗯，谢谢啦，我已经发现这个问题了。
