### ISSUE TITLE
SuperNotCalledException最近老是报这个错

### ISSUE THREAD

**Issue by s3hengwu** [yanzhenjie/AndPermission#508]
android.util.SuperNotCalledException: Activity {com.rest.test/com.yanzhenjie.permission.bridge.BridgeActivity} did not call through to super.onCreate()
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3259)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
    at android.app.ActivityThread.-wrap12(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by s3hengwu** [comment]
是混淆的影响吗？之前没混淆的时候似乎没这个bug

**Comment by yanzhenjie** [comment]
不知道是不是混淆，但是这个super有调用。

**Comment by s3hengwu** [comment]
好奇怪的问题
