### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by githubzaibao** [yanzhenjie/AndPermission#514]
at java.io.UnixFileSystem.createDirectory0(Native method)
at java.io.UnixFileSystem.createDirectory(UnixFileSystem.java:310)
at java.io.File.mkdir(File.java:1316)
at java.io.File.mkdirs(File.java:1343)
at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:2516)
at android.app.ContextImpl.getExternalFilesDirs(ContextImpl.java:650)

locked <0x0c64645a> (a java.lang.Object)
at android.content.ContextWrapper.getExternalFilesDirs(ContextWrapper.java:247)
at com.yanzhenjie.permission.FileProvider.getExternalFilesDirs(FileProvider.java:370)
at com.yanzhenjie.permission.FileProvider.parsePathStrategy(FileProvider.java:209)
at com.yanzhenjie.permission.FileProvider.getPathStrategy(FileProvider.java:167)
locked <0x04ee568b> (a java.util.HashMap)
at com.yanzhenjie.permission.FileProvider.attachInfo(FileProvider.java:87)
at android.app.ActivityThread.installProvider(ActivityThread.java:6647)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:6167)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6068)
at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)

**Comment by Zhaoyuntao** [comment]
作者这个问题解了吗？
