### ISSUE TITLE
纯新手。调用后，没有直接报错，也没有出授权选择框，直接往下走了

### ISSUE THREAD

**Issue by hanfeng1982** [yanzhenjie/AndPermission#54]
我是新手。我的新建项目中没有maven.gradle。直接用Android studio 2.3.2打开组件的demo程序，直接看到
```
Error:(1, 0) Your project path contains non-ASCII characters. This will most likely cause the build to fail on Windows. Please move your project to a different directory. See http://b.android.com/95744 for details. This warning can be disabled by adding the line 'android.overridePathCheck=true' to gradle.properties file in the project directory.
```

直接按照文档上的手顺，自己写的。调用后，没有直接报错，也没有出授权选择框，直接往下走了。但是结果授权没有成功。
运行环境：Android sutdio 2.3.3
模拟器：Nexus_5X_API_24

 代码：
        1:将下载的组件中的`AndPermission-master\permission\src\main\java`中的所有文件拷贝进对应自己项目中的src\main\java目录下。
        2:app/proguard-rules.pro中追加
```
                      -keepclassmembers class ** {
                        @com.yanzhenjie.permission.PermissionYes <methods>;
                       }
                     -keepclassmembers class ** {
                       @com.yanzhenjie.permission.PermissionNo <methods>;
                      }
```
       3:app/build.gradle中
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "cy.a9_2_smsbackup"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.yanzhenjie:permission:1.0.7'
    testCompile 'junit:junit:4.12'
}
```
      4：app/src/main/AndroidManifest.xml中（加了权限：android.permission.READ_SMS，github网上这句好像显示不出来。）
         <uses-permission android:name="android.permission.READ_SMS"/>
      5：Activity中练习代码
          public void backup(View view){
         //程序运行时，这句话正常通过，但是没有任何错误或者框弹出来。
         AndPermission.with(MainActivity.this)
                     .requestCode(100)
                     .permission("android.permission.READ_SMS")
                     .callback(this)
                     .rationale(rationaleListener)
                     .start();
        doBackup();

          }

    //检查到用户上次拒绝过授权后，再次提示用户授权。
```
    private RationaleListener rationaleListener = new RationaleListener() {
        @Override
        public void showRequestPermissionRationale(int requestCode, final Rationale rationale) {
            AlertDialog.Builder builder = new AlertDialog.Builder(MainActivity.this);
            builder.setTitle("友好提醒");
            builder.setMessage("你已拒绝过短信读取权限，备份不了短信，你看着吧");
            builder.setPositiveButton("给你权限", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    //再次调用权限认定
                    rationale.resume();
                }
            });
            builder.setNegativeButton("就不给", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    rationale.cancel();
                }
            });
            builder.show();
        }
    };

    @PermissionYes(100)
    private void getPremissionYes(List<String> grantedPermissions) {
        //即使用户点击了授权，但是国产有些手机还是不能授权成功，所以需要再次确认。
        if(AndPermission.hasPermission(this,"android.permission.READ_SMS")){
            doBackup();
        }else {
            Toast.makeText(this,"授权不成功，请到设置中给程序授权！",Toast.LENGTH_LONG).show();
        }
    }

    @PermissionNo(100)
    private void getPremissionNo(List<String> deniedPermissions){
        Toast.makeText(this,"授权不成功，请到设置中给程序授权！",Toast.LENGTH_LONG).show();
    }


    private void doBackup() {
        //短信数据库已经由内容提供者暴露出来，可以直接解析。
        ContentResolver contentResolver = getContentResolver();
        Uri uri = Uri.parse("content://sms");
        Cursor cursor = contentResolver.query(uri,new String[]{"address","date","body"},null,null,"date asc");
        if (cursor!=null & cursor.getCount()>0){
            while (cursor.moveToNext()){
                String address = cursor.getString(cursor.getColumnIndex("address"));
                String date = cursor.getString(cursor.getColumnIndex("date"));
                String body = cursor.getString(cursor.getColumnIndex("body"));


            }
        }
    }
```

    6:由于授权不成功而直接执行了代码。
    错误如下：点击at android.view.View.performClick(View.java:5610) 打开View.java的时候发现很多红色的。但是其他项目没有发现这种问题。
```
     AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: cy.a9_2_smsbackup, PID: 9269
                                                                 java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                     at android.view.View.performClick(View.java:5610)
                                                                     at android.view.View$PerformClick.run(View.java:22265)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                     at android.view.View.performClick(View.java:5610) 
                                                                     at android.view.View$PerformClick.run(View.java:22265) 
                                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                  Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms from pid=9269, uid=10120 requires android.permission.READ_SMS, or grantUriPermission()
                                                                     at android.os.Parcel.readException(Parcel.java:1683)
                                                                     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                     at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                     at android.content.ContentResolver.query(ContentResolver.java:530)
                                                                     at android.content.ContentResolver.query(ContentResolver.java:472)
                                                                     at cy.a9_2_smsbackup.MainActivity.doBackup(MainActivity.java:85)
                                                                     at cy.a9_2_smsbackup.MainActivity.backup(MainActivity.java:37)
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                     at android.view.View.performClick(View.java:5610) 
                                                                     at android.view.View$PerformClick.run(View.java:22265) 
                                                                     at android.os.Handler.handleCallback(Handler.java:751) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

**Comment by hanfeng1982** [comment]
将代码改成下面后，就可以成功弹框和授权了。但是下面练习代码太简陋，希望能够用上高手的组件。请帮忙看看，谢谢！：
public void backup(View view){
        /* AndPermission.with(MainActivity.this)
                     .requestCode(100)
                     .permission("android.permission.READ_SMS")
                     .callback(this)
                     .rationale(rationaleListener)
                     .start(); */

        if(ContextCompat.checkSelfPermission(this,"android.permission.READ_SMS") != PackageManager.PERMISSION_GRANTED){
            ActivityCompat.requestPermissions(MainActivity.this,new String[]{"android.permission.READ_SMS"},100);
        }else{
            doBackup();
        }

    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if(requestCode == 100){
            if( grantResults[0] == PackageManager.PERMISSION_GRANTED){
                doBackup();
            }else {
                Toast.makeText(this,"授权不成功，请到设置中给程序授权！",Toast.LENGTH_LONG).show();
            }
        }
    }

**Comment by yanzhenjie** [comment]
demo我刚下重新下载运行了，完全没有问题，应该是你本地环境的问题，至于上面调用无反应是你代码可能写错了，你在申请后应该等待回调，不应该直接调用代码：
![qq 20170529215933](https://cloud.githubusercontent.com/assets/13534988/26552565/470477aa-44ba-11e7-93ae-ad34dd7c65eb.png)

建议你解决本地环境问题后，打开demo重试！

**Comment by hanfeng1982** [comment]
谢谢你，我再尝试下哈。

**Comment by yanzhenjie** [comment]
有再尝试吗？是否还有问题？

**Comment by hanfeng1982** [comment]
还没有搞定呀。明天下班回家我再研究下吧。毕竟我对android studio和android都不熟悉哈。

**Comment by hanfeng1982** [comment]
可以了，搞定了。谢谢哈
