### ISSUE TITLE
崩溃~~~

### ISSUE THREAD

**Issue by Hommilist** [yanzhenjie/AndPermission#563]
2.0.1正常，2.0.2和2.0.3崩溃如下：

android10
华为p30
项目已使用androidx
min16，target28

2019-12-30 16:34:28.335 11381-11381/com.dongby.android.mmshow.inter E/CrashReport: android.view.InflateException: Binary XML file line #29 in com.dongby.android.mmshow.inter:layout/abc_dialog_title_material: Binary XML file line #29 in com.dongby.android.mmshow.inter:layout/abc_dialog_title_material: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #29 in com.dongby.android.mmshow.inter:layout/abc_dialog_title_material: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:864)
        at android.view.LayoutInflater.createView(LayoutInflater.java:786)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:106)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:940)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:960)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1014)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:726)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at com.yanzhenjie.permission.task.WaitDialog.<init>(WaitDialog.java:32)
        at com.yanzhenjie.permission.task.TaskExecutor.<init>(TaskExecutor.java:36)
        at com.yanzhenjie.permission.runtime.MRequest$2.<init>(MRequest.java:130)
        at com.yanzhenjie.permission.runtime.MRequest.onCallback(MRequest.java:130)
        at com.yanzhenjie.permission.runtime.MRequest.start(MRequest.java:110)
        at com.dongby.android.sdk.util.PermissionUtil.requestPermission(PermissionUtil.java:107)
        at com.dongby.android.sdk.util.PermissionUtil.requestPermission(PermissionUtil.java:84)
        at com.lokinfo.m95xiu.WelcomeActivity$1.handleMessage(WelcomeActivity.java:209)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 15: TypedValue{t=0x2/d=0x7f0400ca a=-1}
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:918)
        at android.view.View.<init>(View.java:5322)
        at android.widget.TextView.<init>(TextView.java:1006)
        at android.widget.TextView.<init>(TextView.java:1000)
        at android.widget.TextView.<init>(TextView.java:996)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:864) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:786) 
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
        at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:106) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:940) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:960) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1014) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:692) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:726) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552) 
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95) 
        at com.yanzhenjie.permission.task.WaitDialog.<init>(WaitDialog.java:32) 
        at com.yanzhenjie.permission.task.TaskExecutor.<init>(TaskExecutor.java:36) 
        at com.yanzhenjie.permission.runtime.MRequest$2.<init>(MRequest.java:130) 
        at com.yanzhenjie.permission.runtime.MRequest.onCallback(MRequest.java:130) 
        at com.yanzhenjie.permission.runtime.MRequest.start(MRequest.java:110) 
        at com.dongby.android.sdk.util.PermissionUtil.requestPermission(PermissionUtil.java:107) 
        at com.dongby.android.sdk.util.PermissionUtil.requestPermission(PermissionUtil.java:84) 
        at com.lokinfo.m95xiu.WelcomeActivity$1.handleMessage(WelcomeActivity.java:209) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by cuibg** [comment]
我感觉这个不是AndPermission的问题，你看看Androix里面控件是不是很多没用替换
