### ISSUE TITLE
小米手机，android Q ANR

### ISSUE THREAD

**Issue by jiajunhui** [yanzhenjie/AndPermission#565]
2019-12-31 20:46:41.479 23058-23377/runtime.cc:630] Runtime aborting...
2019-12-31 20:46:41.479 23058-23377/runtime.cc:630] Dumping all threads without mutator lock held
2019-12-31 20:46:41.479 23058-23377/runtime.cc:630] All threads:
2019-12-31 20:46:41.479 23058-23377/runtime.cc:630] DALVIK THREADS (116):
2019-12-31 20:46:41.479 23058-23377/runtime.cc:630] "pool-14-thread-1" prio=4 tid=115 Runnable
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | group="" sCount=0 dsCount=0 flags=0 obj=0x138e7a50 self=0xae446600
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | sysTid=23377 nice=10 cgrp=default sched=0/0 handle=0x9907c230
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | state=R schedstat=( 7176193 6414017 52 ) utm=0 stm=0 core=5 HZ=100
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | stack=0x98f79000-0x98f7b000 stackSize=1040KB
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | held mutexes= "abort lock" "mutator lock"(shared held)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #00 pc 003075a7 /apex/com.android.runtime/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+78)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #1 pc 003b4aa7 /apex/com.android.runtime/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits>&, bool, BacktraceMap*, bool) const+362)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #2 pc 003b10bf /apex/com.android.runtime/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits>&, bool, BacktraceMap*, bool) const+34)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #3 pc 003ca253 /apex/com.android.runtime/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+618)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #4 pc 003c48cb /apex/com.android.runtime/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+298)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #5 pc 003c3fd1 /apex/com.android.runtime/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits>&, bool)+1452)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #6 pc 0038314f /apex/com.android.runtime/lib/libart.so (art::Runtime::Abort(char const*)+1118)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #7 pc 000084d7 /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+398)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #8 pc 0028d1f3 /apex/com.android.runtime/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1242)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #9 pc 0028d38f /apex/com.android.runtime/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+62)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #10 pc 00282751 /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+40)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #11 pc 0028267b /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::ScopedCheck::CheckNonHeapValue(char, art::(anonymous namespace)::JniValueType)+946)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #12 pc 00280c5d /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+652)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #13 pc 00278505 /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+528)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #14 pc 00015c05 /apex/com.android.runtime/lib/libopenjdk.so (Java_java_io_UnixFileSystem_list0+224)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at java.io.UnixFileSystem.list0(Native method)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at java.io.UnixFileSystem.list(UnixFileSystem.java:346)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at java.io.File.list(File.java:1131)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at com.yanzhenjie.permission.checker.StorageReadTest.test(StorageReadTest.java:42)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at com.yanzhenjie.permission.checker.StrictChecker.checkReadStorage(StrictChecker.java:194)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at com.yanzhenjie.permission.checker.StrictChecker.hasPermission(StrictChecker.java:106)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at com.yanzhenjie.permission.checker.StrictChecker.hasPermission(StrictChecker.java:39)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at com.yanzhenjie.permission.checker.DoubleChecker.hasPermission(DoubleChecker.java:32)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at com.yanzhenjie.permission.runtime.BaseRequest.getDeniedPermissions(BaseRequest.java:119)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at com.yanzhenjie.permission.runtime.MRequest$1.doInBackground(MRequest.java:104)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at com.yanzhenjie.permission.runtime.MRequest$1.doInBackground(MRequest.java:101)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at android.os.AsyncTask$3.call(AsyncTask.java:378)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] at java.lang.Thread.run(Thread.java:919)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630]
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] "main" prio=4 tid=1 Native
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | group="" sCount=1 dsCount=0 flags=1 obj=0x74a12b20 self=0xf5d71e00
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | sysTid=23058 nice=-4 cgrp=default sched=0/0 handle=0xf618adc0
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | state=S schedstat=( 927394269 152298966 1135 ) utm=76 stm=16 core=7 HZ=100
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | stack=0xff38e000-0xff390000 stackSize=8192KB
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] | held mutexes=
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] kernel: (couldn't read /proc/self/task/23058/stack)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #00 pc 0004f7d8 /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #1 pc 000e48f1 /apex/com.android.runtime/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+88)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #2 pc 004250ad /apex/com.android.runtime/lib/libart.so (_ZN3artL12GoToRunnableEPNS_6ThreadE.llvm.17768113659977041478+332)
2019-12-31 20:46:41.480 23058-23377/runtime.cc:630] native: #3 pc 00424f39 /apex/com.android.runtime/lib/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+8)

**Comment by jiajunhui** [comment]
找到问题了，是组合权限申请引起的问题，把权限拆分开申请就没问题了。
