### ISSUE TITLE
Cannot load library: soinfo_link_image

### ISSUE THREAD

**Issue by jagopy** [yanzhenjie/AndPermission#58]
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1649): could not load library "libiconv.so" needed by "libzbar.so"; caused by load_library(linker.cpp:747): library "libiconv.so" not found
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                              at java.lang.System.loadLibrary(System.java:535)
                                                                              at com.yanzhenjie.zbar.ImageScanner.<clinit>(ImageScanner.java:39)
                                                                              at com.yanzhenjie.zbar.camera.CameraScanAnalysis.<init>(CameraScanAnalysis.java:48)
                                                                              at com.yanzhenjie.zbar.camera.CameraPreview.<init>(CameraPreview.java:48)
                                                                              at com.yanzhenjie.zbar.camera.CameraPreview.<init>(CameraPreview.java:41)

**Comment by yanzhenjie** [comment]
This exception is irrelevant to this project.
