### ISSUE TITLE
在三星手机使用没用混淆的时候就会报这个错误

### ISSUE THREAD

**Issue by xiaoshi316** [yanzhenjie/AndPermission#59]
`06-06 11:33:44.213 5441-5441/com.handpay.zztong.hx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.handpay.zztong.hx, PID: 5441
                                                                     java.lang.NoClassDefFoundError: com.yanzhenjie.permission.AndPermission
                                                                         at com.handpay.zztong.hp.login.activity.LoginActivity.initPermission(LoginActivity.java:156)
                                                                         at com.handpay.zztong.hp.login.activity.LoginActivity.onCreate(LoginActivity.java:80)
                                                                         at android.app.Activity.performCreate(Activity.java:5406)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2362)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2460)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:164)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                         at android.os.Looper.loop(Looper.java:193)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5542)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:657)
                                                                         at dalvik.system.NativeStart.main(Native Method)`

**Comment by yanzhenjie** [comment]
不太清楚，是不是方法数超了65535，如果是按照这个解决试试：  
[http://blog.csdn.net/yanzhenjie1003/article/details/51818269](http://blog.csdn.net/yanzhenjie1003/article/details/51818269)
