### ISSUE TITLE
部分手机必现第一次申请权限时，应用崩溃。第二次调用又恢复正常

### ISSUE THREAD

**Issue by LiuLinXin** [yanzhenjie/AndPermission#610]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.yanzhenjie.permission.bridge.BridgeActivity}: java.lang.NullPointerException: throw with null exception
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2977)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3114)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6831)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
Caused by: java.lang.NullPointerException: throw with null exception
    at com.common.obusi.b.execStartActivity(Unknown Source:150)
    at android.app.Activity.startActivityForResult(Activity.java:5340)
    at android.app.Activity.requestPermissions(Activity.java:4546)
    at com.yanzhenjie.permission.bridge.BridgeActivity.onCreate(BridgeActivity.java:131)
    at android.app.Activity.performCreate(Activity.java:7224)
    at android.app.Activity.performCreate(Activity.java:7213)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
    at com.common.obusi.b.callActivityOnCreate(Unknown Source:2)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
    ... 11 more
java.lang.NullPointerException: throw with null exception
    at com.common.obusi.b.execStartActivity(Unknown Source:150)
    at android.app.Activity.startActivityForResult(Activity.java:5340)
    at android.app.Activity.requestPermissions(Activity.java:4546)
    at com.yanzhenjie.permission.bridge.BridgeActivity.onCreate(BridgeActivity.java:131)
    at android.app.Activity.performCreate(Activity.java:7224)
    at android.app.Activity.performCreate(Activity.java:7213)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
    at com.common.obusi.b.callActivityOnCreate(Unknown Source:2)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3114)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6831)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)

**Comment by LiuLinXin** [comment]
版本分布 Android7 - android 9
出现问题比较多的机型 小米6、小米8、vivo X20、华为nov
权限Manifest.permission.CAMERA
调用AndPermission.with(context)
                .runtime()
                .permission(permission)
                .onDenied(new Action<List<String>>() {
                    @Override
                    public void onAction(List<String> data) {
                        listener.onFailed(0,data);
                    }
                })
                .onGranted(new Action<List<String>>() {
                    @Override
                    public void onAction(List<String> data) {
                        listener.onSucceed(0,data);
                    }
                }).start();
直接崩溃出现上面的错误

bug出现频率挺高的
