### ISSUE TITLE
Receiver not registered

### ISSUE THREAD

**Issue by qyxghcl** [yanzhenjie/AndPermission#617]
java.lang.RuntimeException: Error receiving broadcast Intent { act=me.suncloud.marrymemo.andpermission.bridge.Thread-21 flg=0x10 } in android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1407)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by : java.lang.IllegalArgumentException: Receiver not registered: 
	android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1275)
	android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1514)
	android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:669)
	com.hunliji.hlj_permission.bridge.Messenger.unRegister(Messenger.java:50)
	com.hunliji.hlj_permission.bridge.RequestExecutor.onCallback(RequestExecutor.java:115)
	com.hunliji.hlj_permission.bridge.Messenger.onReceive(Messenger.java:55)

**Comment by qyxghcl** [comment]
Messenger中unRegister的时候提示未注册，麻烦帮忙看一下为什么
