### ISSUE TITLE
IllegalArgumentException: View=DecorView@49190ed not attached to window manager

### ISSUE THREAD

**Issue by erdayeniu** [yanzhenjie/AndPermission#627]
java.lang.IllegalArgumentException: View=DecorView@49190ed[ChatMessageActivity] not attached to window manager
    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:578)
    at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:470)
    at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:172)
    at android.app.Dialog.dismissDialog(Dialog.java:547)
    at android.app.Dialog.dismiss(Dialog.java:527)
    at com.yanzhenjie.permission.task.TaskExecutor.onPostExecute(TaskExecutor.java:49)
    at android.os.AsyncTask.finish(AsyncTask.java:755)
    at android.os.AsyncTask.access$900(AsyncTask.java:192)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8147)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by erdayeniu** [comment]
手机型号：华为 Mate 20 Pro
Android系统版本： Android 10
targetSdkVersion：29
权限：Permissions.RECORD_AUDIO

**Comment by erdayeniu** [comment]
com.yanzhenjie:permission:2.0.3

**Comment by safaribest** [comment]
这种一般是 你activity 已经消失了，你又去请求了权限，检查是否有 postDelay 这种操作。

**Comment by feibix33** [comment]
@liangsaifei 你说的是一种情况，另外假如说acitivy还在的时候请求了，此时关闭这个activity后，请求回来了，也会报错了，最好在库里兼容下这个情况比较好

**Comment by feibix33** [comment]
@yanzhenjie ,辛苦兼容下上面说的这个问题
