### ISSUE TITLE
申请 Notification 权限时崩溃

### ISSUE THREAD

**Issue by CoderWzl** [yanzhenjie/AndPermission#658]
2021-02-09 14:36:57.812 4012-4012/com.yanzhenjie.permission.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yanzhenjie.permission.sample:permission, PID: 4012
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yanzhenjie.permission.sample/com.yanzhenjie.permission.bridge.BridgeActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APP_NOTIFICATION_SETTINGS dat=package:com.yanzhenjie.permission.sample (has extras) }
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3504)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3643)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APP_NOTIFICATION_SETTINGS dat=package:com.yanzhenjie.permission.sample (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
        at android.app.Activity.startActivityForResult(Activity.java:5319)
        at android.app.Activity.startActivityForResult(Activity.java:5263)
        at com.yanzhenjie.permission.bridge.BridgeActivity.startActivityForResult(BridgeActivity.java:194)
        at com.yanzhenjie.permission.bridge.BridgeActivity.onCreate(BridgeActivity.java:168)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3479)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3643) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:238) 
        at android.app.ActivityThread.main(ActivityThread.java:7798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 
2021-02-09 14:36:57.901 2711-2711/com.yanzhenjie.permission.sample E/ActivityThread: Activity com.yanzhenjie.permission.sample.app.MainActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.Messenger@f7c74dc that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.yanzhenjie.permission.sample.app.MainActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.Messenger@f7c74dc that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1682)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1408)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1540)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1513)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1501)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:638)
        at com.yanzhenjie.permission.bridge.Messenger.register(Messenger.java:45)
        at com.yanzhenjie.permission.bridge.RequestExecutor.run(RequestExecutor.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-02-09 14:36:57.906 557-557/? E/SELinux: avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1930 scontext=u:r:system_server:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0
2021-02-09 14:36:57.912 2711-2711/com.yanzhenjie.permission.sample E/ActivityThread: Activity com.yanzhenjie.permission.sample.app.MainActivity has leaked ServiceConnection com.yanzhenjie.permission.bridge.RequestExecutor$1@1c0f9e5 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.yanzhenjie.permission.sample.app.MainActivity has leaked ServiceConnection com.yanzhenjie.permission.bridge.RequestExecutor$1@1c0f9e5 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1914)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1786)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1765)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1776)
        at android.app.ContextImpl.bindService(ContextImpl.java:1705)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:716)
        at com.yanzhenjie.permission.bridge.RequestExecutor.run(RequestExecutor.java:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by CoderWzl** [comment]
2.0.3 版本
