### ISSUE TITLE
Unable to start activity ComponentInfo{com.hikvision.petrel.video/com.yanzhenjie.permission.PermissionActivity}

### ISSUE THREAD

**Issue by guiying712** [yanzhenjie/AndPermission#72]
红米note4，

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.hikvision.petrel.video, PID: 24578
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hikvision.petrel.video/com.yanzhenjie.permission.PermissionActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.lbe.security.miui (has extras) }
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2547)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2613)
                                                                                at android.app.ActivityThread.access$900(ActivityThread.java:180)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                at android.os.Looper.loop(Looper.java:207)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5710)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
                                                                             Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.lbe.security.miui (has extras) }
                                                                                at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
                                                                                at android.app.Instrumentation.execStartActivity(Instrumentation.java:1641)
                                                                                at android.app.Activity.startActivityForResult(Activity.java:4596)
                                                                                at android.app.Activity.requestPermissions(Activity.java:3863)
                                                                                at com.yanzhenjie.permission.PermissionActivity.onCreate(PermissionActivity.java:49)
                                                                                at android.app.Activity.performCreate(Activity.java:6288)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2500)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2613) 
                                                                                at android.app.ActivityThread.access$900(ActivityThread.java:180) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5710) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

**Comment by yanzhenjie** [comment]
是不是方法数超过了64k？

**Comment by guiying712** [comment]
已经使用了MultiDex，其他手机并没有这个问题，红米note4却直接崩溃

**Comment by yanzhenjie** [comment]
现在发布了2.0版本，你可以试用一下2.0版本，如果还有问题，请单独提issue。
