### ISSUE TITLE
java.lang.RuntimeException: Unknown exception code: 1 msg null

### ISSUE THREAD

**Issue by blueZhang** [yanzhenjie/AndPermission#79]
java.lang.RuntimeException: Unknown exception code: 1 msg null
	at android.os.Parcel.readException(Parcel.java:1435)
	at android.os.Parcel.readException(Parcel.java:1379)
	at android.app.ActivityManagerProxy.checkPermission(ActivityManagerNative.java:3141)
	at android.app.ContextImpl.checkPermission(ContextImpl.java:1598)
	at android.content.ContextWrapper.checkPermission(ContextWrapper.java:500)
	at com.e.a.d.a(PermissionUtils.java:66)
	at com.e.a.d.b(PermissionUtils.java:53)
	at com.e.a.b.a(ImplPermission.java:84)

调用 
static int checkPermission(Object o, String permission) {
        return getContext(o).checkPermission(permission, android.os.Process.myPid(), android.os.Process.myUid());
    }

报错 在android4.2.2 手机上

**Comment by yanzhenjie** [comment]
1. 你用的哪个版本。
2. 报错的是AndPermission库的代码吗？
3. 是否是使用了混淆引起？

**Comment by blueZhang** [comment]
我使用的是1.0.3 

报错是在：PermissionUtils.java:66 行代码：
    static int checkPermission(Object o, String permission) {
        return getContext(o).checkPermission(permission, android.os.Process.myPid(), android.os.Process.myUid());
    }
应该不是混淆引起的

**Comment by yanzhenjie** [comment]
可是...可是...可是现在都1.0.8了。
